version: "2"
services:
  redis:
    image: redis
    networks:
      - backend

  db:
    image: postgres:9.4
    networks:
      - backend

  vote:
    image: dockersamples/examplevotingapp_vote
    ports:
      - 5000:80
    links:
      - redis
    networks:
      - frontend
      - backend

  result:
    image: dockersamples/examplevotingapp_result
    ports:
      - 5001:80
    links:
      - db
    networks:
      - frontend
      - backend
  worker:
    image: dockersamples/examplevotingapp_worker
    links:
      - db
      - redis
    networks:
      - backend

networks:
  frontend:
  backend: